# Generated by Django 5.0.3 on 2024-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agilisium_lsm_app', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
