# Generated by Django 5.0.3 on 2024-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agilisium_lsm_app', '0004_user_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('material', models.FileField(blank=True, null=True, upload_to='task_file/')),
            ],
        ),
    ]
