# Generated by Django 5.0.3 on 2024-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agilisium_lsm_app', '0005_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
